
export const FILTER_PRODUCTS_BY_SIZE = "FILTER_PRODUCTS_BY_SIZE";
export const ORDER_PRODUCTS_BY_SIZE = "ORDER_PRODUCTS_BY_SIZE";
export const ADD_TO_CART = "ADD_TO_CART" ;
export const REMOVE_FROM_CART = "REMOVE_FROM_CART" ;
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CLEAR_ORDER = "CLEAR_ORDER";
export const CLEAR_CART = "CLEAR_CART";